# Autogenerated wrapper script for AMReX_jll for aarch64-apple-darwin-mpi+openmpi
export libamrex

using LLVMOpenMP_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("AMReX")
JLLWrappers.@declare_library_product(libamrex, "@rpath/libamrex.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libamrex,
        "lib/libamrex.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
