# Autogenerated wrapper script for AMReX_jll for aarch64-unknown-freebsd-libgfortran5-mpi+mpich
export libamrex

using LLVMOpenMP_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("AMReX")
JLLWrappers.@declare_library_product(libamrex, "libamrex_3d.so")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libamrex,
        "lib/libamrex_3d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
