# Autogenerated wrapper script for AMReX_jll for i686-w64-mingw32-cxx03-mpi+microsoftmpi
export libamrex

using CompilerSupportLibraries_jll
using MicrosoftMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("AMReX")
JLLWrappers.@declare_library_product(libamrex, "libamrex.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libamrex,
        "bin\\libamrex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
