# Autogenerated wrapper script for AMReX_jll for x86_64-apple-darwin-mpi+mpich
export libamrex

using HDF5_jll
using LLVMOpenMP_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("AMReX")
JLLWrappers.@declare_library_product(libamrex, "@rpath/libamrex_3d.dylib")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, LLVMOpenMP_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libamrex,
        "lib/libamrex_3d.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
