# Autogenerated wrapper script for AMReX_jll for x86_64-unknown-freebsd-mpi+openmpi
export libamrex

using HDF5_jll
using LLVMOpenMP_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("AMReX")
JLLWrappers.@declare_library_product(libamrex, "libamrex.so")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, LLVMOpenMP_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libamrex,
        "lib/libamrex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
